# Site settings
title: VR's Notebook
description: "My thoughts and stuff"
url: ""
author:
  name: "VR"
  email: "hello@example.com"
  url: "http://www.example.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /blog/:year/:month/:day/:title.html
future: true
paginate: 5
paginate_path: /page:num/

gems: [jekyll-paginate]

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "3.1.4"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
